// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/7/2026, 11:16:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/plugins/**/*.{js,ts,mjs}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/composables/**/*.{js,ts,mjs}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/utils/**/*.{js,ts,mjs}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sadokaito/Downloads/自分のホームページ/agent-dashboard/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;